# -*- coding: utf-8 -*-
"""아파매거래량 증가율이 높은 지역 찾기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehIJGYAqPr4zJcvtmt2gyaAcZ9Ue_4uN
"""

import streamlit as st
import pandas as pd
from pathlib import Path
from datetime import datetime

# ==============================================================================
# 1. 유틸리티 함수 정의: 월 계산 및 컬럼명 형식 지정
# ==============================================================================

@st.cache_data
def get_month_string(year, month):
    """'YYYY년 M월' 형태의 문자열을 반환 (파일 컬럼명과 일치하도록 '0' 제거)."""
    return f"{year}년 {month}월"

@st.cache_data
def get_previous_month(year, month):
    """입력된 년/월의 이전 달의 년/월을 계산하여 반환."""
    if month == 1:
        return year - 1, 12
    else:
        return year, month - 1

@st.cache_data
def get_analysis_months(target_year, target_month):
    """
    분석에 필요한 4개 월(타겟 월과 그 이전 3개월)의 년/월 튜플 리스트를 반환합니다.
    """
    month_list = []
    y, m = target_year, target_month

    # 총 4개의 월을 역순으로 저장합니다. (타겟 월부터 시작)
    for _ in range(4):
        month_list.append((y, m))
        y, m = get_previous_month(y, m)

    return month_list[::-1] # 가장 오래된 달부터 순서대로 정렬하여 반환

# ==============================================================================
# 2. 파일 로드 함수 (Streamlit 전용)
# ==============================================================================

@st.cache_data
def load_data(uploaded_file):
    """업로드된 CSV 파일을 읽어 DataFrame을 반환 (cp949, utf-8 순차 시도)."""
    if uploaded_file is None:
        return None

    df = None

    # 파일 로드 시도 (cp949와 utf-8 순차 시도)
    for encoding_type in ['cp949', 'utf-8']:
        try:
            # BytesIO를 사용하여 메모리에서 직접 파일 로드
            df = pd.read_csv(uploaded_file, encoding=encoding_type, header=0)

            # 파일 로드 성공 시, 파일 포인터를 다시 처음으로 돌려 다음 시도에 영향을 주지 않도록 함
            uploaded_file.seek(0)
            return df
        except Exception:
            # 실패 시 다음 인코딩 시도
            uploaded_file.seek(0)
            continue

    return None

# ==============================================================================
# 3. 데이터 분석 및 결과 반환 함수
# ==============================================================================

def run_analysis(df, input_year, input_month):
    """실제 데이터 분석 로직을 수행하고 결과를 반환합니다."""

    analysis_months_tuple = get_analysis_months(input_year, input_month)
    analysis_month_names = [get_month_string(y, m) for y, m in analysis_months_tuple]

    # 컬럼명 정리 (공백 -> 밑줄)
    df.columns = df.columns.str.replace(r'\s+', '_', regex=True).str.strip()
    trade_cols_underscore = [col.replace(' ', '_') for col in analysis_month_names]

    REGION_COL_KEY = '지역통합'

    if REGION_COL_KEY not in df.columns:
        return f"[오류] 파일에 필수 컬럼 ('{REGION_COL_KEY}')이 없습니다.", None

    # 필요한 컬럼만 선택
    required_cols = [REGION_COL_KEY] + trade_cols_underscore
    missing_cols = [col for col in required_cols if col not in df.columns]

    if missing_cols:
        return f"[오류] 분석에 필요한 월별 데이터가 부족합니다. 파일에 {missing_cols} 컬럼이 없습니다. (현재 파일 컬럼: {list(df.columns)})", None

    df_analysis = df[required_cols].copy()
    df_analysis.columns = ['지역명'] + analysis_month_names
    trade_months = analysis_month_names

    # '전국' 행 및 결측값 제거
    df_analysis = df_analysis[df_analysis['지역명'].notna()]
    df_analysis = df_analysis[~df_analysis['지역명'].astype(str).str.contains('전국')]

    # 거래건수 컬럼을 숫자형으로 변환
    for col in trade_months:
        df_analysis[col] = df_analysis[col].astype(str).str.replace(r'["\s,]', '', regex=True)

    df_analysis[trade_months] = df_analysis[trade_months].apply(pd.to_numeric, errors='coerce')

    # 데이터 유효성 검사
    if df_analysis[trade_months].isnull().all().all():
        return "[오류] 선택된 기간의 거래량 데이터가 모두 비어있거나 숫자 형식으로 변환할 수 없습니다.", None

    # 전월 대비 거래량 증가 비율 계산
    df_pct_change = df_analysis[trade_months].pct_change(axis=1)

    # 비율 컬럼명 정의
    pct_change_cols = []
    for i in range(1, len(trade_months)):
        prev_month = trade_months[i-1]
        curr_month = trade_months[i]
        pct_change_col_name = f"{prev_month} 대비 {curr_month} 증가율 (%)"
        pct_change_cols.append(pct_change_col_name)

    df_results = df_analysis[['지역명']].copy()
    df_results[pct_change_cols] = df_pct_change.iloc[:, 1:].values * 100

    # 가장 최근 월의 증가율 컬럼을 기준으로 TOP 10 지역 선정
    recent_pct_col = pct_change_cols[-1]

    # NaN 값은 0으로 처리하여 순위 선정에서 제외되거나 하위에 위치하도록 함
    top_10_results = df_results.fillna(0).nlargest(10, recent_pct_col)

    # 최종 출력 포맷팅 (결측값은 '-'로 표시)
    for col in pct_change_cols:
        top_10_results[col] = top_10_results[col].map(lambda x: '{:,.2f}%'.format(x) if x != 0 else '-')

    return None, top_10_results.set_index('지역명')


# ==============================================================================
# 4. Streamlit 메인 앱 실행
# ==============================================================================

def main():
    st.set_page_config(layout="wide", page_title="아파트 매매 거래 분석기")
    st.title("🏡 아파트 매매 거래량 변화 분석기")
    st.markdown("---")

    # -------------------
    # 4-1. 사이드바 (사용자 입력)
    # -------------------
    st.sidebar.header("1. 데이터 파일 업로드")
    uploaded_file = st.sidebar.file_uploader(
        "파일 (CSV)을 업로드해주세요.",
        type="csv",
        help="파일 이름은 '(월) 행정구역별 아파트매매거래현황.csv' 구조와 유사해야 합니다."
    )

    st.sidebar.header("2. 분석 기준 월 설정")
    current_year = datetime.now().year

    # 년도 입력
    input_year = st.sidebar.number_input(
        "기준 년도 (YYYY)",
        min_value=2010,
        max_value=current_year + 1,
        value=current_year,
        step=1
    )

    # 월 입력
    input_month = st.sidebar.selectbox(
        "기준 월 (MM)",
        options=range(1, 13),
        index=datetime.now().month - 1
    )

    # -------------------
    # 4-2. 데이터 로드 및 분석 실행
    # -------------------
    if uploaded_file is None:
        st.info("좌측 사이드바에 분석할 CSV 파일을 업로드해주세요.")
        return

    # 데이터 로드
    df = load_data(uploaded_file)

    if df is None:
        st.error("파일 로드에 실패했습니다. 파일이 유효한 CSV 형식인지, 인코딩 문제(cp949, utf-8)가 없는지 확인해주세요.")
        return

    # 분석 실행
    with st.spinner("데이터를 분석 중입니다..."):
        error_message, top_10_results_df = run_analysis(df, input_year, input_month)

    # -------------------
    # 4-3. 결과 출력
    # -------------------
    if error_message:
        st.error(error_message)
    elif top_10_results_df is not None:

        # 분석 기간 정보
        analysis_months_tuple = get_analysis_months(input_year, input_month)
        analysis_month_names = [get_month_string(y, m) for y, m in analysis_months_tuple]

        recent_month = analysis_month_names[-1]

        st.header(f"🥇 {recent_month} 기준 전월 대비 증가율 TOP 10 지역 분석 결과")
        st.subheader(f"📅 분석 기간: {analysis_month_names[0]} ~ {recent_month} (4개월 데이터 기준)")
        st.caption(f"선정 기준: {top_10_results_df.columns[-1]} (가장 최근 월의 전월 대비 증가율)")
        st.markdown("---")

        # 결과 데이터프레임 출력
        st.dataframe(
            top_10_results_df,
            use_container_width=True
        )

if __name__ == "__main__":
    main()